const $ = (id) => document.querySelector(id);

// Variables de HTML
const navCategories = $('#nav-bar--selections')
const mainPoster = $('#trending-article')
const nextMovieArrow = $('#nextMovie')
const previuosMovieArrow = $('#previuosMovie')
const popularContainer = $('#popular-container')
const topRateContainer = $('#top-rate-container')
const upcomingContainer = $('#upcoming-container')
const searchBar = $('#search_bar')
const search = $('#search')
const searchButton = $('#search-button')
const trending = $('#trending')
const completeMovieListSection = $('#completeMovieListSection')
const backButton = $('#backButton')
const seeMoreButtonPopular = $('#seeMoreButtonPopular')
const seeMoreButtonTopRate = $('#seeMoreButtonTopRate')
const seeMoreButtonUpcoming = $('#seeMoreButtonUpcoming')
const navTitleSection = $('#nav-title--section')
const movieSectionContainer = $('#movieSectionContainer')
const nav = $('#nav')
const selectList = $('#categories')
const options = $('#options')
const detailsSection = $('#detailsSection')
const detailsPosterContainer = $('#detailsPoster-container')
const detailsPoster = $('#detailsPoster')
const year = $('#year')
const rate =$('#rate')
const detailsPosterTitle = $('#detailsPoster-title')
const overview = $('#overview')
const genreDetails = $('#genres')
const similarTitles = $('#similarTitles')